main: HM.LuckyDemon.HMPlugin
version: 1.0.0
name: HMPlugin
author: LuckyDemons
api-version: 1.21

commands:
  hm:
    description: Comando principal del plugin
    usage: /hm [day|items|awake|mensaje|lives|resetlives|addlife|reducestorm|resetdifficulty]
    aliases: [permadeath]
  hmreload:
    description: Recarga la configuración del plugin
    usage: /<command>
    aliases: [hmr, permadeathreload]
    permission: hmplugin.reload
    permission-message: No tienes permiso para usar este comando.

permissions:
  hmplugin.reload:
    description: Permite recargar la configuración del plugin
    default: op